site_name: SpendWise
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - content.code.copy
  palette:
    - scheme: default
      primary: emerald
      accent: sky
    - scheme: slate
      primary: emerald
      accent: sky
extra_css:
  - assets/stylesheets/extra.css

nav:
  - Home: index.md
  - Vis√£o Geral: overview/about.md
  - Backend: backend/index.md
  - Frontend: frontend/index.md
  - Docker & DevOps: docker/index.md
  - API: api/auth.md
